apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tj0ph1nz1-java-quarkus-gitops
  description: This is GitOps manifest for tj0ph1nz1-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=tj0ph1nz1-java-quarkus
    backstage.io/kubernetes-id: tj0ph1nz1-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: tj0ph1nz1-java-quarkus-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tj0ph1nz1-java-quarkus
