apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tj0ph1nz1-java-quarkus
  janus-idp.io/tekton: tj0ph1nz1-java-quarkus
  backstage.io/kubernetes-id: tj0ph1nz1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tj0ph1nz1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
